global:
  domain: cloud.obara.xyz

scribblers:
  controllers:
    scribblers:
      strategy: Recreate
      containers:
        main:
          image:
            repository: biosmarcel/scribble.rs
            tag: 'v0.9.7'
            pullPolicy: IfNotPresent

  service:
    scribblers:
      controller: scribblers
      ports:
        http:
          port: 8080

  ingress:
    scribblers:
      annotations:
        kubernetes.io/ingress.class: traefik
        gethomepage.dev/href: "https://scribble.{{ .Values.global.domain }}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Scribble.Rs"
        gethomepage.dev/description: "online tools to simplify everyday tasks"
        gethomepage.dev/group: "Games"
      className: "traefik"
      hosts:
        - host: scribble.{{ .Values.global.domain }}
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: scribblers
                port: http

