apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tylerobara/oracle-cluster.git
    path: apps/_base
    targetRevision: HEAD
    helm:
      valueFiles:
      - ../cluster/cluster.yaml
      - ../monitoring/monitoring.yaml
      - ../development/development.yaml
      - ../storage/storage.yaml
  syncPolicy:
    automated:
      enabled: true
    syncOptions:
     - FailOnSharedResource=true
  destination:
    name: in-cluster
    namespace: argocd