clusterSecretStore:
  name: oracle-cluster-secret-store
  namespace: external-secrets
  provider:
    vault:
      server: "http://openbao.openbao.svc.cluster.local:8200"
      path: "oracle"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "bao-token"
          namespace: "external-secrets"
          key: "token"